//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registeration
    {
        public int Id { get; set; }
        public int TravelingId { get; set; }
        public int PassengerId { get; set; }
        public string Source { get; set; }
        public string Destination { get; set; }
    
        public virtual Passenger Passenger { get; set; }
        public virtual Traveling Traveling { get; set; }
    }
}
